### PR TITLE
Fix `plot_top_loadings()`

### LINKED ISSUE #14: Ordering categories in `plot_top_loadings()` does not work anymore
I don't believe that the [munging we have here in the learntidymodels package](https://github.com/tidymodels/learntidymodels/blob/ed7910b360d80f76502ee586a3f2d0ac7ce735f1/R/plot_top_loadings.R#L66-L67) to order bars works anymore:

``` r
library(learntidymodels)
#> Loading required package: tidyverse
#> Loading required package: tidymodels
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
library(tidymodels)
library(ggplot2)

data("cells", package = "modeldata")
```

``` r
cell_pca <-
   recipe(class ~ ., data = cells %>% dplyr::select(-case)) %>%
   step_center(all_predictors()) %>%
   step_scale(all_predictors()) %>%
   step_pca(all_predictors())
```

``` r
cell_pca <- prep(cell_pca)

plot_top_loadings(cell_pca, grepl("ch_1", terms) & component_number <= 4, n = 10)
```

<sup>Created on 2021-08-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I do have [different versions of this type of functionality in tidytext](https://juliasilge.github.io/tidytext/reference/reorder_within.html), if we want to use that instead, but tidytext seems like a heavy and ridiculous dependency for this.

### PR DESCRIPTION
**Pull request by juliasilge**
Closes #14 

After looking at this in detail, I'm not sure if this function ever worked, actually.

Here are the new results:

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
library(learntidymodels)
#> Loading required package: tidyverse
library(ggplot2)
theme_set(theme_minimal())


data("cells", package = "modeldata")
cell_pca <-
    recipe(class ~ ., data = cells %>% dplyr::select(-case)) %>%
    step_center(all_predictors()) %>%
    step_scale(all_predictors()) %>%
    step_pca(all_predictors())

cell_pca <- prep(cell_pca)

plot_top_loadings(cell_pca, grepl("ch_1", terms) & component_number <= 4, n = 10)
```

<sup>Created on 2021-08-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

File: tests/testthat/test-loading-data.R [hunk 1]
```diff
@@ -91,7 +91,7 @@ test_that('PLS recipe with no options', {
 test_that('PLS workflow with no options', {
     raw_pls <-
         pls_workflow %>%
-        pull_workflow_prepped_recipe() %>%
+        extract_recipe() %>%
```
Comment (topepo) [inline tests/testthat/test-loading-data.R:94]: We'll probably need a version constraint in the description file to use these (I'm in favor).
